### PR TITLE
Wrap internal exceptions in public API

### LINKED ISSUE #239: BQ connector shouldn't throw shaded internal exceptions.
This is from a StackOverflow [question](https://stackoverflow.com/questions/57414647/why-is-dataproc-using-this-weird-shaded-version-of-the-json-package-and-how-do-i). I think the problem is that, BQ connector shouldn't throw shaded internal exceptions, because it made users hard to catch the exception. Instead it should create its own exception class, e.g., BqConnectorException and set the shaded internal exceptions as cause.

### PR DESCRIPTION
**Pull request by medb**
Fixes #239

### CODE REVIEW

**Comment by functicons** [comment]
I don't quite understand this change. In the stackoverflow question, the user was trying to catch `GoogleJsonResponseException`, but in your change, you didn't catch it.

**Comment by medb** [comment]
> GoogleJsonResponseException

It addresses SO issue, because `GoogleJsonResponseException` is a subclass of `IOException`.

**Comment by functicons** [comment]
> > GoogleJsonResponseException
> 
> It addresses SO issue, because `GoogleJsonResponseException` is a subclass of `IOException`.

But that means we don't need this change, the user can simply catch `IOException`.

**Comment by medb** [comment]
> But that means we don't need this change, the user can simply catch `IOException`.

Technically we need, because this change will make immediately thrown exceptions consistent between shaded and non-shaded JARs.

**Comment by AndyClausen** [comment]
Thank you <3

**Pull request merged**
